### ISSUE TITLE
Purpose of the package

### ISSUE THREAD

**Issue by mumin91** [softwaregroup-bg/ut-emv#12]
I am currently working on a project where I need to make merchant QR code based on EMV format data. For that, I am looking for a package which can convert strings to EMV format. I have looked at your package ut-emv. But  I am a little bit confused whether it can serve my purpose.

**Comment by Kristiyan-Todorov** [comment]
Purpose of the package is to transform BER-TLV EMV string to object and vice versa.

For example, "5A09000000000000000000" would be decoded to 
```json
{
    "pan": {
        "tag": "5A",
        "len": 9,
        "val": "000000000000000000"
    }
}
```

Respectively, 
```json
{
    "pan": {
         "val": "000000000000000000"
    }
}
```
would be encoded to "5A09000000000000000000".

Additionally, there is flatten / unflatten functionality if you wish to have the data in {"key": "value"} format.

The package supports primitive tags, constructed tags, long length tags and data object lists (DOL).
